/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.args;

import org.rwtodd.args.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ArgsTests {
    @Test void testAccumulator() {
        final var verbose = new AccumulatingParam("verbose", 'v', "Be more verbose (can repeat this arg)");
        final var p = new Parser(verbose, new HelpParam());
        var extras = p.parse("-vvvv", "-v");
        assertTrue(extras.isEmpty());
        assertEquals(5, verbose.getValue());
    }
}
